/*
 * Synthetic journal events.
 *
 * Built with the bridge's own encoders and with the layouts in
 * docs/bridge-protocol.md -- deliberately not with anything from `web/`. A
 * fixture generated by the code under test agrees with that code by
 * construction and would keep agreeing with it while both drifted away from the
 * protocol. This is the same reasoning that put test-vectors/ outside both
 * implementations.
 *
 * The shapes here are the ones the protocol actually produces: a message that is
 * queued by the budget before it is delivered, a retry that gives up, telemetry
 * and position from a peer, and a status body.
 */

import { EventCode } from "@protocol/opcodes";
import {
  encodePosition,
  encodeStatus,
  encodeTelemetry,
  encodeText,
  FrameType,
} from "@protocol/payloads";

export interface SynthEvent {
  /** The journal entry's own counter (D10). */
  journalCounter: number;
  direction: "rx" | "tx";
  opcode: number;
  body: Uint8Array;
  receivedAt: Date;
}

function writer(length: number): { bytes: Uint8Array; view: DataView } {
  const bytes = new Uint8Array(length);
  return { bytes, view: new DataView(bytes.buffer) };
}

/** EVT_FRAME_RX: counter u32, src u16, type u8, rssi i16, snr i8, len u8, payload. */
export function frameRx(options: {
  journal: number;
  counter: number;
  src: number;
  type: number;
  rssi: number;
  snr: number;
  payload: Uint8Array;
  at: Date;
}): SynthEvent {
  const { bytes, view } = writer(11 + options.payload.length);
  view.setUint32(0, options.counter, true);
  view.setUint16(4, options.src, true);
  view.setUint8(6, options.type);
  view.setInt16(7, options.rssi, true);
  view.setInt8(9, options.snr);
  view.setUint8(10, options.payload.length);
  bytes.set(options.payload, 11);
  return {
    journalCounter: options.journal,
    direction: "rx",
    opcode: EventCode.FrameRx,
    body: bytes,
    receivedAt: options.at,
  };
}

/** EVT_FRAME_TX_RESULT: counter u32, dst u16, seq u8, result u8, attempts u8, rssi i16, snr i8. */
export function frameTxResult(options: {
  journal: number;
  counter: number;
  dst: number;
  seq: number;
  result: number;
  attempts: number;
  rssi: number;
  snr: number;
  at: Date;
}): SynthEvent {
  const { bytes, view } = writer(12);
  view.setUint32(0, options.counter, true);
  view.setUint16(4, options.dst, true);
  view.setUint8(6, options.seq);
  view.setUint8(7, options.result);
  view.setUint8(8, options.attempts);
  view.setInt16(9, options.rssi, true);
  view.setInt8(11, options.snr);
  return {
    journalCounter: options.journal,
    direction: "tx",
    opcode: EventCode.FrameTxResult,
    body: bytes,
    receivedAt: options.at,
  };
}

/** EVT_BUDGET: band u8, usedMs u32, limitMs u32, nextTxUnix u32. */
export function budget(options: {
  journal: number;
  band: number;
  usedMs: number;
  limitMs: number;
  nextTxUnix: number;
  at: Date;
}): SynthEvent {
  const { bytes, view } = writer(13);
  view.setUint8(0, options.band);
  view.setUint32(1, options.usedMs, true);
  view.setUint32(5, options.limitMs, true);
  view.setUint32(9, options.nextTxUnix, true);
  return {
    journalCounter: options.journal,
    direction: "rx",
    opcode: EventCode.Budget,
    body: bytes,
    receivedAt: options.at,
  };
}

export function status(options: {
  journal: number;
  batteryMv: number;
  uptimeS: number;
  queueDepth?: number;
  band?: number;
  budgetUsedMs?: number;
  budgetLimitMs?: number;
  flags?: number;
  at: Date;
}): SynthEvent {
  return {
    journalCounter: options.journal,
    direction: "rx",
    opcode: EventCode.Status,
    body: encodeStatus({
      batteryMv: options.batteryMv,
      uptimeS: options.uptimeS,
      queueDepth: options.queueDepth ?? 0,
      band: options.band ?? 0,
      budgetUsedMs: options.budgetUsedMs ?? 0,
      budgetLimitMs: options.budgetLimitMs ?? 360_000,
      flags: options.flags ?? 0b011,
    }),
    receivedAt: options.at,
  };
}

/** EVT_FIX: lat i32, lon i32, alt i16, hdop u8, fixAge u8, satellites u8. */
export function fix(options: {
  journal: number;
  latE7: number;
  lonE7: number;
  altM: number;
  hdop: number;
  at: Date;
}): SynthEvent {
  const { bytes, view } = writer(13);
  view.setInt32(0, options.latE7, true);
  view.setInt32(4, options.lonE7, true);
  view.setInt16(8, options.altM, true);
  view.setUint8(10, options.hdop);
  view.setUint8(11, 3);
  view.setUint8(12, 9);
  return {
    journalCounter: options.journal,
    direction: "rx",
    opcode: EventCode.Fix,
    body: bytes,
    receivedAt: options.at,
  };
}

/** EVT_CONFIG_APPLIED: configVersion u32, appliedMask u32, unappliedTypes[]. */
export function configApplied(options: {
  journal: number;
  configVersion: number;
  appliedMask: number;
  unapplied?: number[];
  at: Date;
}): SynthEvent {
  const unapplied = options.unapplied ?? [];
  const { bytes, view } = writer(8 + unapplied.length);
  view.setUint32(0, options.configVersion, true);
  view.setUint32(4, options.appliedMask, true);
  bytes.set(Uint8Array.from(unapplied), 8);
  return {
    journalCounter: options.journal,
    direction: "rx",
    opcode: EventCode.ConfigApplied,
    body: bytes,
    receivedAt: options.at,
  };
}

const BASE = Date.UTC(2026, 7, 31, 6, 0, 0);
const at = (offsetS: number) => new Date(BASE + offsetS * 1000);

/**
 * A short run of a node's life that exercises every projection: a peer position
 * and telemetry, an inbound text, an outbound text that the budget queues before
 * it is delivered, a second outbound that gives up after three attempts, a
 * status and a budget report, and a config acknowledgement.
 */
export function realisticRun(peerNodeId = 0x0002): SynthEvent[] {
  return [
    status({ journal: 1, batteryMv: 4102, uptimeS: 120, queueDepth: 0, at: at(0) }),
    fix({ journal: 2, latE7: 472_692_000, lonE7: 114_041_000, altM: 574, hdop: 12, at: at(30) }),
    frameRx({
      journal: 3,
      counter: 8801,
      src: peerNodeId,
      type: FrameType.Position,
      rssi: -91,
      snr: 7,
      payload: encodePosition({
        latitudeE7: 472_712_345,
        longitudeE7: 114_038_765,
        altitudeM: 512,
        hdop: 9,
        fixAgeS: 4,
      }),
      at: at(60),
    }),
    frameRx({
      journal: 4,
      counter: 8802,
      src: peerNodeId,
      type: FrameType.Telemetry,
      rssi: -95,
      snr: 5,
      payload: encodeTelemetry({
        temperatureCentiC: 1842,
        humidityCentiPercent: 5510,
        pressurePa: 95_320,
        batteryMv: 3987,
        uptimeS: 86_400,
      }),
      at: at(90),
    }),
    frameRx({
      journal: 5,
      counter: 8803,
      src: peerNodeId,
      type: FrameType.Text,
      rssi: -88,
      snr: 9,
      payload: encodeText("at the summit"),
      at: at(120),
    }),
    // One frame, three journal entries. The budget holds it, then it goes out.
    // CLAUDE.md 2.4: the UI has to tell "queued until HH:MM" from "in flight"
    // from "undelivered", and D10 is what lets both entries survive ingestion.
    frameTxResult({
      journal: 6, counter: 501, dst: peerNodeId, seq: 11,
      result: 2, attempts: 0, rssi: 0, snr: 0, at: at(150),
    }),
    budget({
      journal: 7, band: 0, usedMs: 184_000, limitMs: 360_000,
      nextTxUnix: Math.floor(at(210).getTime() / 1000), at: at(150),
    }),
    frameTxResult({
      journal: 8, counter: 501, dst: peerNodeId, seq: 11,
      result: 0, attempts: 1, rssi: -90, snr: 6, at: at(215),
    }),
    // And one that gives up. CLAUDE.md 2.4: "not silently dropped".
    frameTxResult({
      journal: 9, counter: 502, dst: peerNodeId, seq: 12,
      result: 1, attempts: 3, rssi: 0, snr: 0, at: at(400),
    }),
    configApplied({
      journal: 10, configVersion: 7, appliedMask: 0b0000_1111, unapplied: [0x09], at: at(430),
    }),
    status({
      journal: 11, batteryMv: 4088, uptimeS: 550, queueDepth: 1,
      budgetUsedMs: 190_000, budgetLimitMs: 360_000, at: at(500),
    }),
  ];
}

export const synthBase = BASE;
