#!/usr/bin/env python3
"""Turn test-vectors/*.json into a C++ header of byte arrays.

The vectors are shared between the firmware and the TypeScript bridge, because
docs/bridge-protocol.md is implemented on both sides and a protocol only holds if
both agree byte for byte. TypeScript reads the JSON directly; the firmware test
build gets this header instead -- a JSON parser has no business in a firmware
test, and pulling one in would mean the C++ side is really testing the parser.

What it deliberately does NOT emit: the decoded field values. Each implementation
writes its own struct literal and checks that encoding it yields the shared bytes.
If either side has misread a field width or an endianness, its encode does not
match and the test fails. Emitting a generated struct would let both sides inherit
the same mistake from this script.

  tools/gen_vectors.py --out build/generated/test_vectors.h
"""

import argparse
import json
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
VECTOR_DIR = os.path.join(REPO_ROOT, "test-vectors")


def collect(path):
    """Every object anywhere in the file that has both a name and bytes."""
    found = []

    def walk(node):
        if isinstance(node, dict):
            if "name" in node and "bytes" in node:
                found.append((node["name"], node["bytes"]))
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    with open(path, encoding="utf-8") as handle:
        walk(json.load(handle))
    return found


def c_identifier(text):
    return "".join(ch if ch.isalnum() else "_" for ch in text)


def emit_kotlin(entries, out_path, file_count):
    """The same vectors as a Kotlin object.

    A byte array literal rather than a parsed resource: the Android client's
    tests must not depend on a JSON library to check a protocol, for the same
    reason the C++ side does not. Kotlin's Byte is signed, so 0xC0 is written as
    a truncating conversion rather than as a literal the compiler would reject.
    """
    lines = [
        "// Generated by tools/gen_vectors.py from test-vectors/*.json.",
        "// Do not edit: edit the JSON, which the firmware and the PWA also read.",
        "package io.github.juice_de_orange.maxlcommunicator.protocol",
        "",
        "/** One shared test vector: the bytes, and where they came from. */",
        "data class Vector(val group: String, val name: String, val bytes: ByteArray) {",
        "    override fun equals(other: Any?): Boolean =",
        "        other is Vector && group == other.group && name == other.name &&",
        "            bytes.contentEquals(other.bytes)",
        "",
        "    override fun hashCode(): Int = 31 * (31 * group.hashCode() + name.hashCode()) +",
        "        bytes.contentHashCode()",
        "}",
        "",
        "object Vectors {",
        "    val all: List<Vector> = listOf(",
    ]
    for group, name, data in entries:
        body = ", ".join("0x{:02x}.toByte()".format(b) for b in data)
        lines.append(
            '        Vector("{}", "{}", byteArrayOf({})),'.format(group, name, body)
        )
    lines += [
        "    )",
        "",
        "    private val byName: Map<String, Vector> = all.associateBy { it.name }",
        "",
        "    /**",
        "     * Look one up by name.",
        "     *",
        "     * Returns null rather than throwing, and every caller is expected to assert on",
        "     * it: a silently missing vector is a test that passes for the wrong reason.",
        "     */",
        "    fun find(name: String): Vector? = byName[name]",
        "}",
        "",
    ]
    with open(out_path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(
        "gen_vectors: {} vectors from {} file(s) -> {} (kotlin)".format(
            len(entries), file_count, out_path
        )
    )
    return 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True)
    parser.add_argument(
        "--lang",
        choices=("cpp", "kotlin"),
        default="cpp",
        help=(
            "Output language. C++ for the firmware and its host tests, Kotlin for the "
            "Android client. Same JSON, so all three implementations are checked against "
            "the same bytes -- which is the only way 'client-independent' is verifiable "
            "rather than merely asserted."
        ),
    )
    parser.add_argument(
        "--group",
        action="append",
        default=None,
        help=(
            "Only emit this group (the JSON file's base name). Repeatable. "
            "The host test build wants all of them; the firmware's boot self "
            "test wants two, and carrying the bridge and payload vectors into a "
            "device image would be a few kilobytes of flash for nothing."
        ),
    )
    args = parser.parse_args()

    files = sorted(
        name for name in os.listdir(VECTOR_DIR) if name.endswith(".json")
    )
    if args.group:
        wanted = set(args.group)
        unknown = wanted - {os.path.splitext(name)[0] for name in files}
        if unknown:
            print(
                "gen_vectors: no such group(s): {}".format(", ".join(sorted(unknown))),
                file=sys.stderr,
            )
            return 1
        files = [name for name in files if os.path.splitext(name)[0] in wanted]

    entries = []
    for filename in files:
        group = os.path.splitext(filename)[0]
        seen = set()
        for name, hexbytes in collect(os.path.join(VECTOR_DIR, filename)):
            if name in seen:
                print(
                    "gen_vectors: duplicate vector name {!r} in {}".format(name, filename),
                    file=sys.stderr,
                )
                return 1
            seen.add(name)
            try:
                data = bytes.fromhex(hexbytes)
            except ValueError:
                print(
                    "gen_vectors: {} vector {!r} has invalid hex".format(filename, name),
                    file=sys.stderr,
                )
                return 1
            entries.append((group, name, data))

    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)

    if args.lang == "kotlin":
        return emit_kotlin(entries, args.out, len(files))

    lines = [
        "// Generated by tools/gen_vectors.py from test-vectors/*.json.",
        "// Do not edit: edit the JSON, which is also what the TypeScript bridge reads.",
        "#ifndef MAXL_GENERATED_TEST_VECTORS_H",
        "#define MAXL_GENERATED_TEST_VECTORS_H",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "namespace vectors {",
        "",
        "struct Vector {",
        "    const char *group;",
        "    const char *name;",
        "    const uint8_t *bytes;",
        "    size_t length;",
        "};",
        "",
    ]

    for group, name, data in entries:
        symbol = "k_{}_{}".format(c_identifier(group), c_identifier(name))
        body = ", ".join("0x{:02x}".format(b) for b in data)
        # A zero-length array is not valid C++, so an empty vector gets one
        # padding byte that `length` never exposes.
        if not data:
            body = "0x00"
        lines.append(
            "inline constexpr uint8_t {}[] = {{{}}};".format(symbol, body)
        )

    lines += ["", "inline constexpr Vector kAll[] = {"]
    for group, name, data in entries:
        symbol = "k_{}_{}".format(c_identifier(group), c_identifier(name))
        lines.append(
            '    {{"{}", "{}", {}, {}}},'.format(group, name, symbol, len(data))
        )
    lines += [
        "};",
        "",
        "inline constexpr size_t kCount = sizeof(kAll) / sizeof(kAll[0]);",
        "",
        "/// Look a vector up by name. Returns nullptr if it is not there, which the",
        "/// tests assert on -- a silently missing vector is a test that passes for the",
        "/// wrong reason.",
        "inline const Vector *find(const char *name)",
        "{",
        "    for (size_t i = 0; i < kCount; ++i) {",
        "        const char *a = kAll[i].name;",
        "        const char *b = name;",
        "        while (*a != '\\0' && *a == *b) {",
        "            ++a;",
        "            ++b;",
        "        }",
        "        if (*a == '\\0' && *b == '\\0') {",
        "            return &kAll[i];",
        "        }",
        "    }",
        "    return nullptr;",
        "}",
        "",
        "} // namespace vectors",
        "",
        "#endif // MAXL_GENERATED_TEST_VECTORS_H",
        "",
    ]

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))

    print(
        "gen_vectors: {} vectors from {} file(s) -> {}".format(
            len(entries), len(files), args.out
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
